{"name": "unsuccessful sign-in -- @1.1 User data", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x00000001052ae65c chromedriver + 4318812\n1   chromedriver                        0x00000001052a6d00 chromedriver + 4287744\n2   chromedriver                        0x0000000104ed87ec chromedriver + 296940\n3   chromedriver                        0x0000000104f16048 chromedriver + 548936\n4   chromedriver                        0x0000000104f4ed28 chromedriver + 781608\n5   chromedriver                        0x0000000104f0a178 chromedriver + 500088\n6   chromedriver                        0x0000000104f0afc0 chromedriver + 503744\n7   chromedriver                        0x000000010526ec40 chromedriver + 4058176\n8   chromedriver                        0x0000000105273160 chromedriver + 4075872\n9   chromedriver                        0x0000000105236e68 chromedriver + 3829352\n10  chromedriver                        0x0000000105273c4c chromedriver + 4078668\n11  chromedriver                        0x000000010524bf08 chromedriver + 3915528\n12  chromedriver                        0x0000000105290140 chromedriver + 4194624\n13  chromedriver                        0x00000001052902c4 chromedriver + 4195012\n14  chromedriver                        0x00000001052a04d0 chromedriver + 4261072\n15  libsystem_pthread.dylib             0x00000001a0347fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001a0342da0 thread_start + 8\n\n", "trace": "  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/signin_steps.py\", line 34, in step_impl\n    error_message = context.signin.error_message_is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/signin_page.py\", line 45, in error_message_is_displayed\n    return self.is_displayed(self.__error_message)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 33, in is_displayed\n    return self.find(locator).is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 12, in find\n    self.wait_until_element_is_visible(locator, timeout)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 29, in wait_until_element_is_visible\n    wait.until(ec.visibility_of_element_located(locator))\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user navigate to conduit sign-in page", "status": "passed", "start": 1693363195577, "stop": 1693363195939}, {"name": "Given The user validate the page title", "status": "passed", "start": 1693363195939, "stop": 1693363195942}, {"name": "When the user fills in the form with \"16test@test.com.com.bv\" \"None\"", "status": "passed", "start": 1693363195942, "stop": 1693363196101}, {"name": "Then the user should see error message on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x00000001052ae65c chromedriver + 4318812\n1   chromedriver                        0x00000001052a6d00 chromedriver + 4287744\n2   chromedriver                        0x0000000104ed87ec chromedriver + 296940\n3   chromedriver                        0x0000000104f16048 chromedriver + 548936\n4   chromedriver                        0x0000000104f4ed28 chromedriver + 781608\n5   chromedriver                        0x0000000104f0a178 chromedriver + 500088\n6   chromedriver                        0x0000000104f0afc0 chromedriver + 503744\n7   chromedriver                        0x000000010526ec40 chromedriver + 4058176\n8   chromedriver                        0x0000000105273160 chromedriver + 4075872\n9   chromedriver                        0x0000000105236e68 chromedriver + 3829352\n10  chromedriver                        0x0000000105273c4c chromedriver + 4078668\n11  chromedriver                        0x000000010524bf08 chromedriver + 3915528\n12  chromedriver                        0x0000000105290140 chromedriver + 4194624\n13  chromedriver                        0x00000001052902c4 chromedriver + 4195012\n14  chromedriver                        0x00000001052a04d0 chromedriver + 4261072\n15  libsystem_pthread.dylib             0x00000001a0347fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001a0342da0 thread_start + 8\n\n", "trace": "  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/signin_steps.py\", line 34, in step_impl\n    error_message = context.signin.error_message_is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/signin_page.py\", line 45, in error_message_is_displayed\n    return self.is_displayed(self.__error_message)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 33, in is_displayed\n    return self.find(locator).is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 12, in find\n    self.wait_until_element_is_visible(locator, timeout)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 29, in wait_until_element_is_visible\n    wait.until(ec.visibility_of_element_located(locator))\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "c6f52e39-b79f-4029-8a91-7cf36f6e7830-attachment.png", "type": "image/png"}], "start": 1693363196102, "stop": 1693363201389}], "parameters": [{"name": "email", "value": "16test@test.com.com.bv"}, {"name": "password", "value": "None"}], "start": 1693363194377, "stop": 1693363201467, "uuid": "2f5cce1e-06c6-4eb7-acf7-997d28d97aaf", "historyId": "c968da454e096f27a3e809698bc32247", "fullName": "User sign-in: unsuccessful sign-in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "User sign-in"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}