{"name": "unsuccessful sign-in -- @1.5 User data", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x000000010093665c chromedriver + 4318812\n1   chromedriver                        0x000000010092ed00 chromedriver + 4287744\n2   chromedriver                        0x00000001005607ec chromedriver + 296940\n3   chromedriver                        0x000000010059e048 chromedriver + 548936\n4   chromedriver                        0x00000001005d6d28 chromedriver + 781608\n5   chromedriver                        0x0000000100592178 chromedriver + 500088\n6   chromedriver                        0x0000000100592fc0 chromedriver + 503744\n7   chromedriver                        0x00000001008f6c40 chromedriver + 4058176\n8   chromedriver                        0x00000001008fb160 chromedriver + 4075872\n9   chromedriver                        0x00000001008bee68 chromedriver + 3829352\n10  chromedriver                        0x00000001008fbc4c chromedriver + 4078668\n11  chromedriver                        0x00000001008d3f08 chromedriver + 3915528\n12  chromedriver                        0x0000000100918140 chromedriver + 4194624\n13  chromedriver                        0x00000001009182c4 chromedriver + 4195012\n14  chromedriver                        0x00000001009284d0 chromedriver + 4261072\n15  libsystem_pthread.dylib             0x00000001a0347fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001a0342da0 thread_start + 8\n\n", "trace": "  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/signin_steps.py\", line 34, in step_impl\n    error_message = context.signin.error_message_is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/signin_page.py\", line 45, in error_message_is_displayed\n    return self.is_displayed(self.__error_message)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 33, in is_displayed\n    return self.find(locator).is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 12, in find\n    self.wait_until_element_is_visible(locator, timeout)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 29, in wait_until_element_is_visible\n    wait.until(ec.visibility_of_element_located(locator))\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user navigate to conduit sign-in page", "status": "passed", "start": 1693362785103, "stop": 1693362785483}, {"name": "Given The user validate the page title", "status": "passed", "start": 1693362785483, "stop": 1693362785485}, {"name": "When the user fills in the form with \"16test@test.com.com.bv\" \"test@test\"", "status": "passed", "start": 1693362785485, "stop": 1693362785674}, {"name": "Then the user should see error message on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x000000010093665c chromedriver + 4318812\n1   chromedriver                        0x000000010092ed00 chromedriver + 4287744\n2   chromedriver                        0x00000001005607ec chromedriver + 296940\n3   chromedriver                        0x000000010059e048 chromedriver + 548936\n4   chromedriver                        0x00000001005d6d28 chromedriver + 781608\n5   chromedriver                        0x0000000100592178 chromedriver + 500088\n6   chromedriver                        0x0000000100592fc0 chromedriver + 503744\n7   chromedriver                        0x00000001008f6c40 chromedriver + 4058176\n8   chromedriver                        0x00000001008fb160 chromedriver + 4075872\n9   chromedriver                        0x00000001008bee68 chromedriver + 3829352\n10  chromedriver                        0x00000001008fbc4c chromedriver + 4078668\n11  chromedriver                        0x00000001008d3f08 chromedriver + 3915528\n12  chromedriver                        0x0000000100918140 chromedriver + 4194624\n13  chromedriver                        0x00000001009182c4 chromedriver + 4195012\n14  chromedriver                        0x00000001009284d0 chromedriver + 4261072\n15  libsystem_pthread.dylib             0x00000001a0347fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001a0342da0 thread_start + 8\n\n", "trace": "  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/signin_steps.py\", line 34, in step_impl\n    error_message = context.signin.error_message_is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/signin_page.py\", line 45, in error_message_is_displayed\n    return self.is_displayed(self.__error_message)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 33, in is_displayed\n    return self.find(locator).is_displayed()\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 12, in find\n    self.wait_until_element_is_visible(locator, timeout)\n  File \"/Users/dayanebahia/PycharmProjects/seleniumBehave/features/page_objects/base_page.py\", line 29, in wait_until_element_is_visible\n    wait.until(ec.visibility_of_element_located(locator))\n  File \"/Users/dayanebahia/behave/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "8313054c-26bc-406e-b5e3-239e7f6acae8-attachment.png", "type": "image/png"}], "start": 1693362785674, "stop": 1693362790969}], "parameters": [{"name": "email", "value": "16test@test.com.com.bv"}, {"name": "password", "value": "test@test"}], "start": 1693362783920, "stop": 1693362791043, "uuid": "569b1029-72f9-4e81-a1a9-142fdf1463c7", "historyId": "36ac177acf9d13d9bc6076224a3d83f8", "fullName": "User sign-in: unsuccessful sign-in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "User sign-in"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}